### ISSUE TITLE
Bravo!

### ISSUE THREAD

**Issue by DasRabbi** [nicksawhney/bernie-sits#11]
Bravo good sir!

**Comment by nicksawhney** [comment]
Thank you kindly!

**Comment by DasRabbi** [comment]
Where do you go from here with it?

**Comment by nicksawhney** [comment]
Responding to PRs and collaborating with everyone here on what to do going forward! I've mentioned some ideas in https://github.com/nicksawhney/bernie-sits/pull/8#issuecomment-766295945 and I'll be adding some issues to figure out details tomorrow morning.
