### ISSUE TITLE
Breakdown on API Costs

### ISSUE THREAD

**Issue by Jeevantk** [nicksawhney/bernie-sits#17]
Hi, 
Can you give a breakdown of the API cost from google. When I checked the pricing it seems that Streetview API would cost 5.6 dollars per 1000 requests [ $56K USD for 10 million requests]. Also, can you give a breakdown of how much you have got via public donations? Putting these numbers publically can probably help increase trust and further receive funds to help you breakeven in case donations didn't match the costs

**Comment by nicksawhney** [comment]
Good ballpark. I might be at more liberty to discuss specifics in the coming days or weeks. I'm still waiting on confirmation of various financial aspects of this experience, and I'll be able to provide more clarity once I have more myself. I can say though, as a student waking up to some of the charges was definitely a stomach-churning experience. Donations generally kept up with my estimate of total costs -- when they didn't I pulled the core functionality of the site. This happened a couple times throughout the time the site was live. I was very impressed by the amount of support this got! It actually ended up crashing buymeacoffee.com a few times, and they ended up pushing some upgrades to the site to deal with the traffic.

**Comment by Jeevantk** [comment]
Happy to know that most of the costs were covered by donations. Another question I had was on the choice of buymeacoffee for donations where there are service providers that do not take any commission on the donation. [Paypal,ko-fi.com] . I [Just doing some market research on why creators are willing to pay a commission to donation platforms when they are the ones who are driving in the traffic. ]

**Comment by nicksawhney** [comment]
it was super simple to set up buymeacoffee amid a bunch of other time-sensitive issues having to do with scaling and maintenance. I opened the site and donations were coming in within the minute. No frills. The platform sends the money directly to my PayPal so I’m not reliant on a third party for transmission of the funds. Plus, I truly honestly love coffee (specifically cold brew) and if there’s one way I’d like to be tipped for the site, it’s through ☕️☕️☕️☕️

>
