### ISSUE TITLE
Make image fusion in browser 

### ISSUE THREAD

**Issue by hesenp** [nicksawhney/bernie-sits#19]
Hey @nicksawhney ! Good job on making the Bernie meme a spash! My Fb timeline is swamped with funny Bernie memes. 

I was trying to generate my own meme and realized that you pulled the original site due to API cost. I noticed that you are trying to handle the image fusion part in server. Actually this operation would be done in JavaScript in users' browser. As a result your entire site would be statically hosted on free places like Github itself. 

Here's some packages to give you [some rough ideas](https://github.com/lukechilds/merge-images).

Thanks a lot for the fun generating work!

**Comment by keevie** [comment]
https://github.com/nicksawhney/bernie-sits/pull/21 implemented here :)
