### ISSUE TITLE
What's Next?

### ISSUE THREAD

**Issue by JackHowa** [nicksawhney/bernie-sits#20]
> I'm thinking we maintain a relatively original-looking version of the site, and have another branch where we can go absolutely wild with everything people want to contribute -- styling, different images and overlays (like people have been asking for on twitter), changing image placement, all the rest! That version could become a more general open-source web based meme creation app. Would love anyone's thoughts!

(via @nicksawhney  https://github.com/nicksawhney/bernie-sits/pull/8#issuecomment-766295945)

### Keep the site up? I wonder if there's some free way of keeping this up to get to 10M memes

- @heremaps @Tafkas ? 
- leaflet? https://github.com/Leaflet/Leaflet or mapbox @mourner
- google maps? @jpoehnelt

**Comment by keevie** [comment]
I'm sure adding some caching would keep the api costs down too!

**Comment by nicksawhney** [comment]
@keevie Caching is a great idea, creating an issue now. 

For macro-level discussions on the future of this thing, let's use #22 

@JackHowa The main issue with non-maps APIs is that other services don't offer a combination of fuzzy location search and street view images that's as functional as the google API. I think one of the reasons the site was popular was the fact that you didn't have to be super exact with the address. However, I know that there are street view images available for free through services like [mapillary](https://www.mapillary.com/) so a possible solution is to use a different service for the location search and another for the images. I'm not sure if the quality/coverage of other services matches google.

**Comment by nicksawhney** [comment]
#25 for keeping the original viral site alive.

**Comment by jpoehnelt** [comment]
I can take a look tomorrow at the code to see about optimizations. Seems there are some conversations already occurring about cost/credits/etc.

**Comment by MisteeAmber** [comment]
I purchase the app now how to I get the Bernie meme on the picture?

**Comment by nicksawhney** [comment]
The app is not available for purchase. If you sent a donation to my
crowdfunding page misunderstanding the situation I can totally refund you!

**Comment by MisteeAmber** [comment]
Oh, I thought you had to purchase the GitHub App so I did.
I am not too tech-savvy, and thank you for the quick response!!  😊

**Comment by JackHowa** [comment]
@nicksawhney closing this, not sure if this is still work-in-progress?
