### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by nicksawhney** [nicksawhney/bernie-sits#23]
I'm looking for some insight on how to license this thing. I'd like to be as open as possible with it, open source is awesome and I want others to be able to deploy this site if they want to. However, I have a few preferences (none of which are set in stone) that I'd like to use to guide which license to pick. If anyone has experience with this kind of thing, I'd love your insight! 

- I'd like credit for creating the original site if possible
- I don't love the idea of others making a version of the site with ads and deploying it for themselves 
- I want to encourage open source contribution and creativity 
- I want to protect myself from an [elasticsearch-type-situation](https://www.elastic.co/blog/why-license-change-AWS)

**Comment by mrvenanzi** [comment]
It doesn't necessarily tick all of the boxes (bullets), but Affero GPL may
be a good one to consider, especially for bullet #3.  Affero GPL (GNU AGPLv3)
is both Free Software Foundation (FSF) approved and Open Source Initiative
(OSI) approved.  See highlights/bold/underline for how it would help #3.
Basically, would keep someone from privatizing their own version on their
own server.


*The GNU Affero General Public License is a modified version of the
ordinary GNU GPL version 3. It has one added requirement: if you run a
modified program on a server and let other users communicate with it there,
your server must also allow them to download the source code corresponding
to the modified version running there.*

*----(from *https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License)

*--------*

The purpose of the GNU Affero GPL is to prevent a problem that affects
developers of free programs that are often used on servers.

Suppose you develop and release a free program under the ordinary GNU GPL.
If developer D modifies the program and releases it, the GPL requires him
to distribute his version under the GPL too. Thus, if you get a copy of his
version, you are free to incorporate some or all of his changes into your
own version.

But *suppose the program is mainly useful on servers. *When D modifies the
program, he might very likely run it on his own server and never release
copies. Then you would never get a copy of the source code of his version,
so you would never have the chance to include his changes in your version.
You may not like that outcome.

Using the GNU Affero GPL avoids that outcome.* If D runs his version on a
server that everyone can use, you too can use it. Assuming he has followed
the license requirement to let the server's users download the source code
of his version,* you can do so, and then you can incorporate his changes
into your version. (If he hasn't followed it, you have your lawyer complain
to him.)

---- (from https://www.gnu.org/licenses/why-affero-gpl.html)


*References:*
https://www.gnu.org/licenses/why-affero-gpl.html
https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License

**Comment by mrvenanzi** [comment]
It doesn't necessarily tick all of the boxes (bullets), but Affero GPL may be a good one to consider, especially for bullet #3.  Affero GPL (GNU AGPLv3) is both Free Software Foundation (FSF) approved and Open Source Initiative (OSI) approved.  See highlights/bold/underline for how it would help #3.  Basically, would keep someone from privatizing their own version on their own server.



--------------------------

> The GNU Affero General Public License is a modified version of the ordinary GNU GPL version 3. It has one added requirement: **_if you run a modified program on a server and let other users communicate with it there, your server must also allow them to download the source code corresponding to the modified version running there._**

_(from https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License)_

--------------------------


> The purpose of the GNU Affero GPL is to prevent a problem that affects developers of free programs that are often used on servers.
> 
> Suppose you develop and release a free program under the ordinary GNU GPL. If developer D modifies the program and releases it, the GPL requires him to distribute his version under the GPL too. Thus, if you get a copy of his version, you are free to incorporate some or all of his changes into your own version.
> 
> But **_suppose the program is mainly useful on servers._** When D modifies the program, he might very likely run it on his own server and never release copies. Then you would never get a copy of the source code of his version, so you would never have the chance to include his changes in your version. You may not like that outcome.
> 
> Using the GNU Affero GPL avoids that outcome. **_If D runs his version on a server that everyone can use, you too can use it. Assuming he has followed the license requirement to let the server's users download the source code of his version, you can do so, and then you can incorporate his changes into your version._** (If he hasn't followed it, you have your lawyer complain to him.)

_(from https://www.gnu.org/licenses/why-affero-gpl.html)_

--------------------------

**References:**
https://www.gnu.org/licenses/why-affero-gpl.html
https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License

**Comment by nicksawhney** [comment]
This looks good! I like the idea that they'll have to open source anything they make. Is there anything similar that would ensure that I get credit or that the site can't be deployed with ads? If this is the closest we can get, I'm happy to move forward with this. It seems to hit the main issue at hand, which is people messaging me on twitter trying to privately deploy the entire site for money.

**Comment by samarmohan** [comment]
You should use something that doesn't let people freely copy the site AT ALL. Just a thought, I have no experience with licenses though.

**Comment by nicksawhney** [comment]
Its no fun to keep all this to myself. I'm not trying to turn this thing into my own private ad machine. People are so interested in this, I want to make it available and free to use if they want to! I just want to make sure my own role and credit in its creation is recognized with the app. However, I'm also not married to that idea -- if the best move for open source says otherwise I'm open to it. 

Essentially, with licensing I'm looking for the middle ground between fair credit and free use.

**Comment by nicksawhney** [comment]
Plus, shouldn't a site about Bernie Sanders himself be equally available to all, funded through the collaboration of many?! It would be kind of ironic if not.

**Comment by nicksawhney** [comment]
Resolved with https://github.com/nicksawhney/bernie-sits/commit/3a9f123f6ac564e65b867dd1cdc784ecb3354c38

**Comment by allisonjohnson979** [comment]
@samarmohan, open-source software is for everyone to view and contribute. It doesn't make sense to use a license that doesn't let others modify or use the software. 
Sorry for commenting after 14 days. 😂

**Comment by mrvenanzi** [comment]
Hi @allisonjohnson979 !   Cheers to another new GitHub user! 👍

**Comment by caroldegenhardt** [comment]
STOP
