### ISSUE TITLE
You can use CSS to overlay bernie

### ISSUE THREAD

**Issue by astrowonk** [nicksawhney/bernie-sits#4]
There's no need to do any computation server-side to overlay bernie, or use numpy/cv etc. 

A CSS stylesheet can overlay the bernie.png image directly on top of a div that holds the result from google maps. I'll work on a PR on this in the evening if no one else gets to it.

**Comment by baffalop** [comment]
I think it's good that it's composited as an image. It can be downloaded.

**Comment by samarmohan** [comment]
Agree with @baffalop, it's better server-side.

**Comment by nicksawhney** [comment]
Agreed, lets keep the images.
